CREATE DATABASE Tienda

CREATE TABLE Categoria (
 Id INT IDENTITY (1,1) PRIMARY KEY,
 Nombre NVARCHAR(100) NOT NULL
);
CREATE TABLE Producto (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Nombre VARCHAR(100) NOT NULL,
 Precio DECIMAL(10,2) NOT NULL,
 CategoriaId INT NOT NULL,
 FOREIGN KEY (CategoriaId) REFERENCES Categoria(Id)
);
CREATE TABLE Venta (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Fecha DATE NOT NULL,
 CategoriaId INT NOT NULL,
 ProductoId INT NOT NULL,
 Cantidad INT NOT NULL,
 Cliente VARCHAR(200),
 FOREIGN KEY (ProductoId) REFERENCES Producto(Id)
 
);